name: SpringBoot CI/CD

on:
  pull_request:
    branches: ["develop"]
    types: [closed]

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'corretto'
        
    - name: Grant execute permission for gradlew
      working-directory: ./main
      run: chmod +x gradlew
  
    - name: build with gradle
      working-directory: ./main
      run: ./gradlew clean build

    - name: SSH Deploy to GCP
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: 3080
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/docker_compose 
          sudo docker compose down
          scp -i ${{ secrets.SSH_KEY }} -P ${{ secrets.PORT }} ${{ github.workspace }}/build/libs/*.jar ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/docker_compose/web/
          echo 'y' | sudo docker system prune -a
          sudo docker compose up -d
          
